name: basisbeveiliging exec


on:
  workflow_dispatch:


jobs:
  update-scope:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r engine/requirements.txt

      - name: Run update script
        run: |
          python engine/basisbeveiliging.py scope.txt
          cat scope/rijksoverheid.txt scope.txt | sort -u > scope/rijksoverheid.tmp
          cp scope/rijksoverheid.tmp scope/rijksoverheid.2tmp
          mv scope/rijksoverheid.tmp scope/rijksoverheid.txt
          rm -f scope.txt


      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add -A scope/rijksoverheid.txt scope/rijksoverheid.2tmp
          git commit -m "Auto-update: updated basisbeveiliging" || echo "No changes to commit"
          git push