name: Gist sync

on:
  workflow_run:
    workflows: ["Schedule scan"]
    types:
      - completed

jobs:
  scope-change-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if scope changed
        run: |
          git fetch origin main
          git diff --name-only origin/main HEAD | grep '^scope/' && echo "Scope changed!" || echo "No changes."
