name: Update exec

on:
	workflow_dispatch:

permissions:
	contents: write


jobs:
	update-and-commit:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Set up Python
				uses: actions/setup-python@v4
				with:
					python-version: "3.x"

			- name: Install dependencies
				run: |
					python -m pip install --upgrade pip
					pip install -r requirements.txt

			- name: Run NVD script
				env:

				run: python update.py

			- name: Commit and push changes
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
				run: |
					git config --global user.name "B0b-scanner"
					git config --global user.email "b0b-scanner-bot@users.noreply.github.com"
					git add .
					git commit -m "Update repository with resources" || echo "No changes to commit"
					git push